[project]
name = "wiktionary-extract"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.10.0",
    "tqdm>=4.67.3",
    "unicodedataplus>=16.0.0.post1",
]
